

compile: product.cpp discountedProduct.cpp customer.cpp market.cpp membershipMarket.cpp streetMarket.cpp shoppingCart.cpp main.cpp
			g++ -std=c++11 product.cpp discountedProduct.cpp customer.cpp market.cpp membershipMarket.cpp streetMarket.cpp shoppingCart.cpp main.cpp -o main

run:
		./main2.out